name: reviewdog-suggester
on: pull_request
jobs:
  ktlint:
    if: github.event.pull_request.user.login == 'nikclayton'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Run ktlintFormat
        run: ./gradlew ktlintFormat

      - name: Suggester / ktlintFormat
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: ktlintFormat

permissions:
  contents: read
  issues: write
  pull-requests: write
